# 数据源配置
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.249:3306/ry_cloud?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456